# Generated by Django 5.0.6 on 2024-06-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="members",
            field=models.ManyToManyField(
                blank=True, related_name="workspace_members", to="accounts.profileuser"
            ),
        ),
    ]
