# Generated by Django 5.0.6 on 2024-06-21 20:30

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("images", "0001_initial"),
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BackgorundColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_at",
                    django_jalali.db.models.jDateTimeField(
                        auto_now_add=True, verbose_name="create model"
                    ),
                ),
                (
                    "update_at",
                    django_jalali.db.models.jDateTimeField(
                        auto_now=True, verbose_name="update model"
                    ),
                ),
                ("color", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "create_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "background_color",
                "verbose_name_plural": "background_colors",
                "db_table": "background_color",
            },
        ),
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_at",
                    django_jalali.db.models.jDateTimeField(
                        auto_now_add=True, verbose_name="create model"
                    ),
                ),
                (
                    "update_at",
                    django_jalali.db.models.jDateTimeField(
                        auto_now=True, verbose_name="update model"
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "deleted_at",
                    django_jalali.db.models.jDateTimeField(
                        blank=True, editable=False, null=True
                    ),
                ),
                ("board_title", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "Backgorund_color",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bg_color_board",
                        to="boards.backgorundcolor",
                    ),
                ),
                (
                    "background_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bg_image_board",
                        to="images.images",
                    ),
                ),
                (
                    "create_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workspace_boards",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "board",
                "verbose_name_plural": "boards",
                "db_table": "board",
            },
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_at",
                    django_jalali.db.models.jDateTimeField(
                        auto_now_add=True, verbose_name="create model"
                    ),
                ),
                (
                    "update_at",
                    django_jalali.db.models.jDateTimeField(
                        auto_now=True, verbose_name="update model"
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "deleted_at",
                    django_jalali.db.models.jDateTimeField(
                        blank=True, editable=False, null=True
                    ),
                ),
                ("card_title", models.CharField(max_length=100)),
                ("card_body", models.TextField()),
                ("expire_date", django_jalali.db.models.jDateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "card_status",
                    models.CharField(
                        choices=[
                            ("doing", "doing"),
                            ("done", "done"),
                            ("defined", "defined"),
                        ],
                        max_length=7,
                    ),
                ),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="board_card",
                        to="boards.board",
                    ),
                ),
                (
                    "create_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workspace_card",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "card",
                "verbose_name_plural": "cards",
                "db_table": "card",
            },
        ),
        migrations.CreateModel(
            name="ChatBoard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "board",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="board_chat",
                        to="boards.board",
                    ),
                ),
                (
                    "reply_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reply_chat",
                        to="boards.chatboard",
                    ),
                ),
                (
                    "user",
                    models.ManyToManyField(
                        related_name="profile_chat", to="accounts.profileuser"
                    ),
                ),
                (
                    "workspace",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workpace_chat_board",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "chat board",
                "verbose_name_plural": "chat boards",
                "db_table": "chat_board",
            },
        ),
    ]
