# Generated by Django 5.0.6 on 2024-06-21 21:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("boards", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="backgorundcolor",
            name="create_by",
        ),
        migrations.RemoveField(
            model_name="board",
            name="create_by",
        ),
        migrations.RemoveField(
            model_name="card",
            name="create_by",
        ),
    ]
