# Generated by Django 5.0.6 on 2024-06-21 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boards", "0002_remove_backgorundcolor_create_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="Backgorund_color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bg_color_board",
                to="boards.backgorundcolor",
            ),
        ),
    ]
