# Generated by Django 5.0.6 on 2024-06-21 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boards", "0003_alter_board_backgorund_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatboard",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reply_chat",
                to="boards.chatboard",
            ),
        ),
    ]
